<div style="background-color: darkslategray; color: white; padding: 15px; border-radius: 8px;">
    <center><h1 style="font-family: Arial, sans-serif;">TO GRANT OR NOT TO GRANT: DECIDING ON COMPENSATION BENEFITS</h1></center>
    <center><h3 style="font-family: Arial, sans-serif;">Machine Learning Project</h3></center>
</div>

**<h3>Table of Contents</h3>**
* [1. Environment Setup](#1.-Environment-Setup)
    * [1.1 Importing Libraries](#1.1-Importing-Libraries)
    * [1.2 Importing the data set](#1.2-Importing-the-data-set)
* [2. Exploratory Data Analysis](#2.-Exploratory-Data-Analysis)
    * [2.1 General analysis of the data set](#2.1-General-analysis-of-the-data-set)
    * [2.1.1 Treating duplicates](#2.1.1-Treating-duplicates)
    * [2.1.2 Missing Values](#2.1.2-Missing-Values)
    * [2.1.3 Type conversion](#2.1.3-type-conversion)
    * [2.1.4 Visual Exploration](#2.1.4-visual-exploration)
    * [2.1.5 Numerical features- Univariate analysis](#215-numerical-features---univariate-analysis)
    * [2.1.6 Categorical Features- Univariate Analysis](#216-categorical-features--univariate-analysis)
    * [2.1.7 Multivariate Analysis](#217-multivariate-analysis)
    * [2.1.8 Feature Engineering](#218-feature-engineering)
* [3. Data Preprocessing](#3.-Data-Preprocessing)
    * [3.1 Numerical Data](#31-numerical-data)
    * [3.2 Outliers Treatment](#32-outliers-treatment)
    * [3.3 Categorical Features Preprocessing](#33-categorical-features-preprocessing)
    * [3.4 Data Scaling (Numerical)](#34-data-scaling-numerical)
    * [3.5 Encoding](#35-encoding)
* [4. Models](#4-first-simple-model--random-forest)
    * [4.1 Random Forest](#41-random-forest)

## 1. Environment Setup

### 1.1 Importing libraries

In [1996]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.calibration import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFECV
from sklearn.model_selection import StratifiedKFold

### 1.2 Importing the data set

In [1997]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [1998]:
train_data = pd.read_csv('train_data.csv', index_col='Claim Identifier')
test_data = pd.read_csv('test_data.csv', index_col='Claim Identifier')

C:\Users\isa\AppData\Local\Temp\ipykernel_24172\3470921380.py:1: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data = pd.read_csv('train_data.csv', index_col='Claim Identifier')


In [1999]:
#drop target variable
df = train_data.drop(columns='Claim Injury Type')

## 2. Exploratory Data Analysis

### 2.1 General analysis of the data set

In [2000]:
df.head()

Accident Date  Age at Injury Alternative Dispute Resolution  \
Claim Identifier                                                               
5393875             2019-12-30           31.0                              N   
5393091             2019-08-30           46.0                              N   
5393889             2019-12-06           40.0                              N   
957648180                  NaN            NaN                            NaN   
5393887             2019-12-30           61.0                              N   

                 Assembly Date Attorney/Representative  Average Weekly Wage  \
Claim Identifier                                                              
5393875             2020-01-01                       N                 0.00   
5393091             2020-01-01                       Y              1745.93   
5393889             2020-01-01                       N              1434.80   
957648180           2020-01-01                     NaN                  NaN   
5393887             2020-01-01                       N                  NaN   

                  Birth Year    C-2 Date    C-3 Date  \
Claim Identifier                                       
5393875               1988.0  2019-12-31         NaN   
5393091               1973.0  2020-01-01  2020-01-14   
5393889               1979.0  2020-01-01         NaN   
957648180                NaN         NaN         NaN   
5393887               1958.0  2019-12-31         NaN   

                                  Carrier Name Carrier Type County of Injury  \
Claim Identifier                                                               
5393875             NEW HAMPSHIRE INSURANCE CO  1A. PRIVATE     ST. LAWRENCE   
5393091           ZURICH AMERICAN INSURANCE CO  1A. PRIVATE          WYOMING   
5393889              INDEMNITY INSURANCE CO OF  1A. PRIVATE           ORANGE   
957648180                                  NaN          NaN              NaN   
5393887                   STATE INSURANCE FUND      2A. SIF         DUTCHESS   

                 COVID-19 Indicator District Name First Hearing Date Gender  \
Claim Identifier                                                              
5393875                           N      SYRACUSE                NaN      M   
5393091                           N     ROCHESTER         2020-02-21      F   
5393889                           N        ALBANY                NaN      M   
957648180                       NaN           NaN                NaN    NaN   
5393887                           N        ALBANY                NaN      M   

                  IME-4 Count  Industry Code  \
Claim Identifier                               
5393875                   NaN           44.0   
5393091                   4.0           23.0   
5393889                   NaN           56.0   
957648180                 NaN            NaN   
5393887                   NaN           62.0   

                                          Industry Code Description  \
Claim Identifier                                                      
5393875                                                RETAIL TRADE   
5393091                                                CONSTRUCTION   
5393889           ADMINISTRATIVE AND SUPPORT AND WASTE MANAGEMEN...   
957648180                                                       NaN   
5393887                           HEALTH CARE AND SOCIAL ASSISTANCE   

                 Medical Fee Region  OIICS Nature of Injury Description  \
Claim Identifier                                                          
5393875                           I                                 NaN   
5393091                           I                                 NaN   
5393889                          II                                 NaN   
957648180                       NaN                                 NaN   
5393887                          II                                 NaN   

                  WCIO Cause of I

In [2001]:
df.tail()

Accident Date  Age at Injury Alternative Dispute Resolution  \
Claim Identifier                                                               
327160035                  NaN            NaN                            NaN   
6165075             2022-12-13           72.0                              N   
249875936                  NaN            NaN                            NaN   
120584215                  NaN            NaN                            NaN   
818961390                  NaN            NaN                            NaN   

                 Assembly Date Attorney/Representative  Average Weekly Wage  \
Claim Identifier                                                              
327160035           2022-12-31                     NaN                  NaN   
6165075             2022-12-31                       N                  0.0   
249875936           2022-12-31                     NaN                  NaN   
120584215           2022-12-31                     NaN                  NaN   
818961390           2022-12-31                     NaN                  NaN   

                  Birth Year    C-2 Date C-3 Date  \
Claim Identifier                                    
327160035                NaN         NaN      NaN   
6165075               1950.0  2022-12-31      NaN   
249875936                NaN         NaN      NaN   
120584215                NaN         NaN      NaN   
818961390                NaN         NaN      NaN   

                                   Carrier Name Carrier Type County of Injury  \
Claim Identifier                                                                
327160035                                   NaN          NaN              NaN   
6165075           TECHNOLOGY INSURANCE CO. INC.  1A. PRIVATE         SULLIVAN   
249875936                                   NaN          NaN              NaN   
120584215                                   NaN          NaN              NaN   
818961390                                   NaN          NaN              NaN   

                 COVID-19 Indicator District Name First Hearing Date Gender  \
Claim Identifier                                                              
327160035                       NaN           NaN                NaN    NaN   
6165075                           N    BINGHAMTON                NaN      F   
249875936                       NaN           NaN                NaN    NaN   
120584215                       NaN           NaN                NaN    NaN   
818961390                       NaN           NaN                NaN    NaN   

                  IME-4 Count  Industry Code       Industry Code Description  \
Claim Identifier                                                               
327160035                 NaN            NaN                             NaN   
6165075                   NaN           48.0  TRANSPORTATION AND WAREHOUSING   
249875936                 NaN            NaN                             NaN   
120584215                 NaN            NaN                             NaN   
818961390                 NaN            NaN                             NaN   

                 Medical Fee Region  OIICS Nature of Injury Description  \
Claim Identifier                                                          
327160035                       NaN                                 NaN   
6165075                           I                                 NaN   
249875936                       NaN                                 NaN   
120584215                       NaN                                 NaN   
818961390                       NaN                                 NaN   

                  WCIO Cause of Injury Code  WCIO Cause of Injury Description  \
Claim Identifier                                                                
327160035                               NaN                               NaN   
6165075                                25.0  FROM DIFFERENT LEVEL (ELEVATION) 

In [2002]:
df.shape

(593471, 31)

Surprise we have a whole fucking lot of features with Dtype object

In [2003]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 593471 entries, 5393875 to 818961390
Data columns (total 31 columns):
 #   Column                              Non-Null Count   Dtype  
---  ------                              --------------   -----  
 0   Accident Date                       570337 non-null  object 
 1   Age at Injury                       574026 non-null  float64
 2   Alternative Dispute Resolution      574026 non-null  object 
 3   Assembly Date                       593471 non-null  object 
 4   Attorney/Representative             574026 non-null  object 
 5   Average Weekly Wage                 545375 non-null  float64
 6   Birth Year                          544948 non-null  float64
 7   C-2 Date                            559466 non-null  object 
 8   C-3 Date                            187245 non-null  object 
 9   Carrier Name                        574026 non-null  object 
 10  Carrier Type                        574026 non-null  object 
 11  County of Injury      

we can drop "OIICS Nature of Injury Description" because it doesn´t have any values

In [2004]:
df.drop('OIICS Nature of Injury Description', axis=1,inplace=True)

In [2005]:
df.describe(include='all')

Accident Date  Age at Injury Alternative Dispute Resolution  \
count         570337  574026.000000                         574026   
unique          5539            NaN                              3   
top       2020-03-01            NaN                              N   
freq            1245            NaN                         571412   
mean             NaN      42.114270                            NaN   
std              NaN      14.256432                            NaN   
min              NaN       0.000000                            NaN   
25%              NaN      31.000000                            NaN   
50%              NaN      42.000000                            NaN   
75%              NaN      54.000000                            NaN   
max              NaN     117.000000                            NaN   

       Assembly Date Attorney/Representative  Average Weekly Wage  \
count         593471                  574026         5.453750e+05   
unique          1096                       2                  NaN   
top       2020-03-06                       N                  NaN   
freq            1422                  392291                  NaN   
mean             NaN                     NaN         4.910883e+02   
std              NaN                     NaN         6.092918e+03   
min              NaN                     NaN         0.000000e+00   
25%              NaN                     NaN         0.000000e+00   
50%              NaN                     NaN         0.000000e+00   
75%              NaN                     NaN         8.410000e+02   
max              NaN                     NaN         2.828079e+06   

           Birth Year    C-2 Date    C-3 Date          Carrier Name  \
count   544948.000000      559466      187245                574026   
unique            NaN        2475        1648                  2046   
top               NaN  2021-05-11  2021-04-21  STATE INSURANCE FUND   
freq              NaN        1847         350                111144   
mean      1886.767604         NaN         NaN                   NaN   
std        414.644423         NaN         NaN                   NaN   
min          0.000000         NaN         NaN                   NaN   
25%       1965.000000         NaN         NaN                   NaN   
50%       1977.000000         NaN         NaN                   NaN   
75%       1989.000000         NaN         NaN                   NaN   
max       2018.000000         NaN         NaN                   NaN   

       Carrier Type County of Injury COVID-19 Indicator District Name  \
count        574026           574026             574026        574026   
unique            8               63                  2             8   
top     1A. PRIVATE          SUFFOLK                  N           NYC   
freq         285368            60430             546505        270779   
mean            NaN              NaN                NaN           NaN   
std             NaN              NaN                NaN           NaN   
min             NaN              NaN                NaN           NaN   
25%             NaN              NaN                NaN           NaN   
50%             NaN              NaN                NaN           NaN   
75%             NaN              NaN                NaN           NaN   
max             NaN              NaN                NaN           NaN   

       First Hearing Date  Gender    IME-4 Count  Industry Code  \
count              150798  574026  132803.000000  564068.000000   
unique               1094       4            NaN            NaN   
top            2022-04-15       M            NaN            NaN   
freq                  440  335218            NaN            NaN   
mean                  NaN     NaN       3.207337      58.645305   
std                   NaN     NaN       2.832303      19.644175   
min                   NaN     NaN       1.000000      11.000000   
25%                   NaN     NaN       1.000000      45.000000   
50% 

### 2.1.1 Treating duplicates

We have duplicate values that need to be removed

In [2006]:
#duplicated values
df.duplicated().sum()

18351

Since this all the claims have _`Assembly Date`_ we can assume that in order to have a claim you always have a _`Claim Identifier`_ (that we use as index) and an _`Assembly Date`_. So let's check the rows that only have _`Assembly Date`_ filled, i.e, empty rows.

In [2007]:

only_assembly_date = df.drop(columns=['Assembly Date']).isnull().all(axis=1) & df['Assembly Date'].notnull()


num_only_assembly_date_filled = only_assembly_date.sum()
print(f"Number of rows with only 'Assembly Date' filled: {num_only_assembly_date_filled}")

Number of rows with only 'Assembly Date' filled: 19445


### 2.1.2 Missing Values

In [2008]:
df.isnull().sum()/df.shape[0]*100

Accident Date                         3.898084
Age at Injury                         3.276487
Alternative Dispute Resolution        3.276487
Assembly Date                         0.000000
Attorney/Representative               3.276487
Average Weekly Wage                   8.104187
Birth Year                            8.176137
C-2 Date                              5.729850
C-3 Date                             68.449174
Carrier Name                          3.276487
Carrier Type                          3.276487
County of Injury                      3.276487
COVID-19 Indicator                    3.276487
District Name                         3.276487
First Hearing Date                   74.590502
Gender                                3.276487
IME-4 Count                          77.622664
Industry Code                         4.954412
Industry Code Description             4.954412
Medical Fee Region                    3.276487
WCIO Cause of Injury Code             5.911831
WCIO Cause of

In [2009]:
train_data['C-3 Date'].value_counts(dropna=False)
len(train_data['C-3 Date'].unique())

1649

In [2010]:
train_data['First Hearing Date'].value_counts(dropna=False)

print(len(train_data['First Hearing Date'].unique()))

1095


In [2011]:
train_data['IME-4 Count'].value_counts(dropna=False)

print(len(train_data['IME-4 Count'].unique()))

42


In [2012]:
df.describe(include='O')
  

Accident Date Alternative Dispute Resolution Assembly Date  \
count         570337                         574026        593471   
unique          5539                              3          1096   
top       2020-03-01                              N    2020-03-06   
freq            1245                         571412          1422   

       Attorney/Representative    C-2 Date    C-3 Date          Carrier Name  \
count                   574026      559466      187245                574026   
unique                       2        2475        1648                  2046   
top                          N  2021-05-11  2021-04-21  STATE INSURANCE FUND   
freq                    392291        1847         350                111144   

       Carrier Type County of Injury COVID-19 Indicator District Name  \
count        574026           574026             574026        574026   
unique            8               63                  2             8   
top     1A. PRIVATE          SUFFOLK                  N           NYC   
freq         285368            60430             546505        270779   

       First Hearing Date  Gender          Industry Code Description  \
count              150798  574026                             564068   
unique               1094       4                                 20   
top            2022-04-15       M  HEALTH CARE AND SOCIAL ASSISTANCE   
freq                  440  335218                             114339   

       Medical Fee Region WCIO Cause of Injury Description  \
count              574026                           558386   
unique                  5                               74   
top                    IV                          LIFTING   
freq               265981                            46610   

       WCIO Nature of Injury Description WCIO Part Of Body Description  \
count                             558369                        556944   
unique                                56                            54   
top                       STRAIN OR TEAR               LOWER BACK AREA   
freq                              153373                         51862   

       Zip Code      WCB Decision  
count    545389            574026  
unique    10060                 1  
top       11236  Not Work Related  
freq       3302            574026

### Observations

#### Missing Values ####
OIICS Nature of Injury Description has no values

_`IME-4 Count`_, _`First Hearing Date`_ and _`C-3 Date`_ have >50% of entries missing ( 77.6%, 74.5 and 68.4%, respectively)

#### Single Value Feature ####
The feature _`WCB Decision`_ only has one value along the whole dataset (excluding missing values of course)

#### Categorical features that could be represented as boolean ####
Some categorical variables that only present 2 unique values, usually '1s and 0s' or 'Y or N' could be changed to boolean. Since we are not doing data pre-processing yet, these changes would have to preserve any NaN data. The variables are:
- Agreement Reached (0s and 1s)
- Attorney/Representative (Y or N)
- COVID-19 Indicator (Y or N)

---

### 2.1.3 Type conversion
Here we are converting categorical variables that could be represented as boolean, meaning they only have two unique values, while still perserving the NaN entries present in the dataset.

In [2013]:
#function to transform Y and N into boolean while preserving the NaNs
def transform_strings_in_bool(df, col_names):
    for col_name in col_names:
        df[col_name] = df[col_name].map({'Y': True, 'N': False, np.nan: np.nan})
    return df

In [2014]:
# Agreement Reached only has values of  0s and 1s so lets convert it to boolean
df['Agreement Reached'] = df['Agreement Reached'].astype("boolean")


In [2015]:

df = transform_strings_in_bool(df, ['Attorney/Representative','COVID-19 Indicator'])
print(df['Attorney/Representative'].unique(), df['COVID-19 Indicator'].unique())


[False True nan] [False nan True]


---

### 2.1.4 Visual Exploration

#### Numerical Feature Correlation

In [2016]:
# # Filter the dataframe to include only integer and float columns
# numeric_train_data = train_data.select_dtypes(include=['int64', 'float64'])

# # Calculate the correlation matrix
# correlation_matrix = numeric_train_data.corr()

# # Plot the correlation matrix using matplotlib
# plt.figure(figsize=(12, 10))
# sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='coolwarm', cbar=True)
# plt.title('Correlation Matrix')
# plt.show()

As this heatmap shows, theres not much to say about the correlations between features

#### Outliers

In [2017]:
# numeric_train_data = numeric_train_data.dropna(axis=1, how='all')

# sp_rows = 3
# sp_cols = 2

# fig, axes = plt.subplots(sp_rows, sp_cols, figsize=(20, 11), tight_layout=True)

# features = numeric_train_data.select_dtypes(include=['number']).columns.tolist()

# for ax, feat in zip(axes.flatten(), features):
#     sns.boxplot(x=numeric_train_data[feat], ax=ax)

# title = "Numerical Variables' Boxplots"
# plt.suptitle(title, fontsize=16) 
# plt.show()

In [2018]:
# outlier_date = train_data.copy()
# for col in outlier_date.columns:
#     if 'Date' in col:
#         outlier_date[col] = pd.to_datetime(outlier_date[col], format='%Y-%m-%d')
#     elif 'Year' in col:
#         outlier_date[col] = outlier_date[col].replace(0.0, np.nan)
#         outlier_date[col] = pd.to_datetime(outlier_date[col].dropna().astype(int).astype(str), format='%Y', errors='coerce')

# features = ['Birth Year','C-2 Date','C-3 Date','Assembly Date','Accident Date','First Hearing Date']

# sp_rows = 2
# sp_cols = 3

# fig, axes = plt.subplots(sp_rows, sp_cols, figsize=(20, 11), tight_layout=True)

# for ax, feat in zip(axes.flatten(), features):
#     sns.histplot(outlier_date[feat], ax=ax, bins=30)


# title = "Datetime Variables' Histograms"

# plt.show()

In [2019]:
# sp_rows = 3
# sp_cols = 2

# fig, axes = plt.subplots(sp_rows, sp_cols, figsize=(20, 11), tight_layout=True)

# for ax, feat in zip(axes.flatten(), features):
#     sns.boxplot(x=outlier_date[feat], ax=ax)


# title = "Datetime Variables' Boxplots"
# plt.suptitle(title, fontsize=16)
# plt.show()

#### Fix Birthday Year Nan


In [2020]:
df.isna().sum()

Accident Date                         23134
Age at Injury                         19445
Alternative Dispute Resolution        19445
Assembly Date                             0
Attorney/Representative               19445
Average Weekly Wage                   48096
Birth Year                            48523
C-2 Date                              34005
C-3 Date                             406226
Carrier Name                          19445
Carrier Type                          19445
County of Injury                      19445
COVID-19 Indicator                    19445
District Name                         19445
First Hearing Date                   442673
Gender                                19445
IME-4 Count                          460668
Industry Code                         29403
Industry Code Description             29403
Medical Fee Region                    19445
WCIO Cause of Injury Code             35085
WCIO Cause of Injury Description      35085
WCIO Nature of Injury Code      

In [2021]:
df.head()

Accident Date  Age at Injury Alternative Dispute Resolution  \
Claim Identifier                                                               
5393875             2019-12-30           31.0                              N   
5393091             2019-08-30           46.0                              N   
5393889             2019-12-06           40.0                              N   
957648180                  NaN            NaN                            NaN   
5393887             2019-12-30           61.0                              N   

                 Assembly Date Attorney/Representative  Average Weekly Wage  \
Claim Identifier                                                              
5393875             2020-01-01                   False                 0.00   
5393091             2020-01-01                    True              1745.93   
5393889             2020-01-01                   False              1434.80   
957648180           2020-01-01                     NaN                  NaN   
5393887             2020-01-01                   False                  NaN   

                  Birth Year    C-2 Date    C-3 Date  \
Claim Identifier                                       
5393875               1988.0  2019-12-31         NaN   
5393091               1973.0  2020-01-01  2020-01-14   
5393889               1979.0  2020-01-01         NaN   
957648180                NaN         NaN         NaN   
5393887               1958.0  2019-12-31         NaN   

                                  Carrier Name Carrier Type County of Injury  \
Claim Identifier                                                               
5393875             NEW HAMPSHIRE INSURANCE CO  1A. PRIVATE     ST. LAWRENCE   
5393091           ZURICH AMERICAN INSURANCE CO  1A. PRIVATE          WYOMING   
5393889              INDEMNITY INSURANCE CO OF  1A. PRIVATE           ORANGE   
957648180                                  NaN          NaN              NaN   
5393887                   STATE INSURANCE FUND      2A. SIF         DUTCHESS   

                 COVID-19 Indicator District Name First Hearing Date Gender  \
Claim Identifier                                                              
5393875                       False      SYRACUSE                NaN      M   
5393091                       False     ROCHESTER         2020-02-21      F   
5393889                       False        ALBANY                NaN      M   
957648180                       NaN           NaN                NaN    NaN   
5393887                       False        ALBANY                NaN      M   

                  IME-4 Count  Industry Code  \
Claim Identifier                               
5393875                   NaN           44.0   
5393091                   4.0           23.0   
5393889                   NaN           56.0   
957648180                 NaN            NaN   
5393887                   NaN           62.0   

                                          Industry Code Description  \
Claim Identifier                                                      
5393875                                                RETAIL TRADE   
5393091                                                CONSTRUCTION   
5393889           ADMINISTRATIVE AND SUPPORT AND WASTE MANAGEMEN...   
957648180                                                       NaN   
5393887                           HEALTH CARE AND SOCIAL ASSISTANCE   

                 Medical Fee Region  WCIO Cause of Injury Code  \
Claim Identifier                                                 
5393875                           I                       27.0   
5393091                           I                       97.0   
5393889                          II                       79.0   
957648180                       NaN                        NaN   
5393887                          II                       16.0   

                 WCIO Cause of Injury Description  WCIO Nature of Injury Code  \
Claim Identifie

In [2022]:
df['Accident Date'].head()

Claim Identifier
5393875      2019-12-30
5393091      2019-08-30
5393889      2019-12-06
957648180           NaN
5393887      2019-12-30
Name: Accident Date, dtype: object

#### to date_time object

In [2023]:
# converts the date columns to datetime format
for col in train_data.columns:
    # fist we convert all columns containing the word 'Date' to datetime format
    if 'Date' in col:
        train_data[col] = pd.to_datetime(train_data[col], format='%Y-%m-%d')
    elif 'Year' in col:
        # Replace 0.0 with NaN
        train_data[col] = train_data[col].replace(0.0, np.nan)
        # Convert only non-NaN values to datetime
        train_data[col] = pd.to_datetime(train_data[col].dropna().astype(int).astype(str), format='%Y', errors='coerce')

train_data

Accident Date  Age at Injury Alternative Dispute Resolution  \
Claim Identifier                                                               
5393875             2019-12-30           31.0                              N   
5393091             2019-08-30           46.0                              N   
5393889             2019-12-06           40.0                              N   
957648180                  NaT            NaN                            NaN   
5393887             2019-12-30           61.0                              N   
...                        ...            ...                            ...   
327160035                  NaT            NaN                            NaN   
6165075             2022-12-13           72.0                              N   
249875936                  NaT            NaN                            NaN   
120584215                  NaT            NaN                            NaN   
818961390                  NaT            NaN                            NaN   

                 Assembly Date Attorney/Representative  Average Weekly Wage  \
Claim Identifier                                                              
5393875             2020-01-01                       N                 0.00   
5393091             2020-01-01                       Y              1745.93   
5393889             2020-01-01                       N              1434.80   
957648180           2020-01-01                     NaN                  NaN   
5393887             2020-01-01                       N                  NaN   
...                        ...                     ...                  ...   
327160035           2022-12-31                     NaN                  NaN   
6165075             2022-12-31                       N                 0.00   
249875936           2022-12-31                     NaN                  NaN   
120584215           2022-12-31                     NaN                  NaN   
818961390           2022-12-31                     NaN                  NaN   

                 Birth Year   C-2 Date   C-3 Date  \
Claim Identifier                                    
5393875          1988-01-01 2019-12-31        NaT   
5393091          1973-01-01 2020-01-01 2020-01-14   
5393889          1979-01-01 2020-01-01        NaT   
957648180               NaT        NaT        NaT   
5393887          1958-01-01 2019-12-31        NaT   
...                     ...        ...        ...   
327160035               NaT        NaT        NaT   
6165075          1950-01-01 2022-12-31        NaT   
249875936               NaT        NaT        NaT   
120584215               NaT        NaT        NaT   
818961390               NaT        NaT        NaT   

                                   Carrier Name Carrier Type  \
Claim Identifier                                               
5393875              NEW HAMPSHIRE INSURANCE CO  1A. PRIVATE   
5393091            ZURICH AMERICAN INSURANCE CO  1A. PRIVATE   
5393889               INDEMNITY INSURANCE CO OF  1A. PRIVATE   
957648180                                   NaN          NaN   
5393887                    STATE INSURANCE FUND      2A. SIF   
...                                         ...          ...   
327160035                                   NaN          NaN   
6165075           TECHNOLOGY INSURANCE CO. INC.  1A. PRIVATE   
249875936                                   NaN          NaN   
120584215                                   NaN          NaN   
818961390                                   NaN          NaN   

                 Claim Injury Type County of Injury COVID-19 Indicator  \
Claim Identifier                                                         
5393875                2. NON-COMP     ST. LAWRENCE                  N   
5393091               4. TEMPORARY          WYOMING                  N   
5393889               4. TEMPORARY           ORANGE                  N   
957648180                      NaN              NaN    

In [2024]:
if train_data['Birth Year'].isna().any():
   train_data['Birth Year'] = train_data['Accident Date'].dt.year - train_data['Age at Injury']

train_data['Birth Year'].isna().sum()

23134

In [2025]:
def convert_dates_to_timestamps(df):
    """
    Converts all columns in the DataFrame that contain 'Date' in their name
    to timestamps (seconds since epoch).

    Parameters:
    df (pd.DataFrame): The DataFrame containing date columns.

    Returns:
    pd.DataFrame: DataFrame with 'Date' columns converted to timestamps.
    """
    # Create a copy to avoid modifying the original DataFrame
    df = df.copy()

    for col in df.columns:
        if 'Date' in col:
            # Convert the column to datetime, coerce invalid parsing to NaT
            df[col] = pd.to_datetime(df[col], errors='coerce')

#Convert to timestamp only for valid datetime values
            df[col] = df[col].apply(lambda x: x.timestamp() if pd.notnull(x) else np.nan)

    return df

In [2026]:
train_data = convert_dates_to_timestamps(train_data)
test_data = convert_dates_to_timestamps(test_data)

train_data.describe(include='all')

Accident Date  Age at Injury Alternative Dispute Resolution  \
count    5.703370e+05  574026.000000                         574026   
unique            NaN            NaN                              3   
top               NaN            NaN                              N   
freq              NaN            NaN                         571412   
mean     1.619644e+09      42.114270                            NaN   
std      5.908936e+07      14.256432                            NaN   
min     -2.625696e+08       0.000000                            NaN   
25%      1.600042e+09      31.000000                            NaN   
50%      1.624752e+09      42.000000                            NaN   
75%      1.647821e+09      54.000000                            NaN   
max      1.695946e+09     117.000000                            NaN   

        Assembly Date Attorney/Representative  Average Weekly Wage  \
count    5.934710e+05                  574026         5.453750e+05   
unique            NaN                       2                  NaN   
top               NaN                       N                  NaN   
freq              NaN                  392291                  NaN   
mean     1.626665e+09                     NaN         4.910883e+02   
std      2.721032e+07                     NaN         6.092918e+03   
min      1.577837e+09                     NaN         0.000000e+00   
25%      1.603670e+09                     NaN         0.000000e+00   
50%      1.627517e+09                     NaN         0.000000e+00   
75%      1.650326e+09                     NaN         8.410000e+02   
max      1.672445e+09                     NaN         2.828079e+06   

          Birth Year      C-2 Date      C-3 Date          Carrier Name  \
count   570337.00000  5.594660e+05  1.872450e+05                574026   
unique           NaN           NaN           NaN                  2046   
top              NaN           NaN           NaN  STATE INSURANCE FUND   
freq             NaN           NaN           NaN                111144   
mean      1978.44118  1.626466e+09  1.627335e+09                   NaN   
std         13.97561  3.513655e+07  2.832608e+07                   NaN   
min       1900.00000  8.214048e+08  7.216128e+08                   NaN   
25%       1967.00000  1.604621e+09  1.603757e+09                   NaN   
50%       1979.00000  1.628467e+09  1.626826e+09                   NaN   
75%       1990.00000  1.650931e+09  1.650413e+09                   NaN   
max       2022.00000  1.717200e+09  1.717114e+09                   NaN   

       Carrier Type Claim Injury Type County of Injury COVID-19 Indicator  \
count        574026            574026           574026             574026   
unique            8                 8               63                  2   
top     1A. PRIVATE       2. NON-COMP          SUFFOLK                  N   
freq         285368            291078            60430             546505   
mean            NaN               NaN              NaN                NaN   
std             NaN               NaN              NaN                NaN   
min             NaN               NaN              NaN                NaN   
25%             NaN               NaN              NaN                NaN   
50%             NaN               NaN              NaN                NaN   
75%             NaN               NaN              NaN                NaN   
max             NaN               NaN              NaN                NaN   

       District Name  First Hearing Date  Gender    IME-4 Count  \
count         574026        1.507980e+05  574026  132803.000000   
unique             8                 NaN       4            NaN   
top              NYC                 NaN       M            NaN   
freq          270779                 NaN  335218            NaN   
mean             NaN        1.647666e+09     NaN       3.207337   
std              NaN        3.144186e+07     NaN       2.832303   
min              NaN        1.5

---

### 2.1.8 Feature Engineering

## 3. Data Preprocessing

### checking for claim indetifier that are bigger than usual

In [2027]:
# train_data.index.value_counts()

seems that some identifier have more than 7 numbers in them 

In [2028]:
# claim_ids_over_7_digits = train_data[train_data.index.astype(str).str.len() > 7]

# # Display the result
# claim_ids_over_7_digits.info()

all the value expect the assembly date are null so we can drop them as they don't provide any information

In [2029]:
# train_data = train_data[train_data.index.astype(str).str.len() <= 7]

# # Display the result after dropping
# train_data.info()

doing this removed a lot of null values and now their is columns without any NaN

### Empty rows
In the initial analysis we saw that the only features that has no missing values is `_Assembly Date_`. So let's check how many rows only have that feature filled and the rest of columns empty

In [2030]:
train_data = train_data[~(train_data.drop(columns=['Assembly Date']).isna().all(axis=1) & train_data['Assembly Date'].notna())]
X_test = test_data[~(test_data.drop(columns=['Assembly Date']).isna().all(axis=1) & test_data['Assembly Date'].notna())]

In [2031]:
only_assembly_date = train_data.drop(columns=['Assembly Date']).isnull().all(axis=1) & df['Assembly Date'].notnull()


num_only_assembly_date_filled = only_assembly_date.sum()
print(f"Number of rows with only 'Assembly Date' filled: {num_only_assembly_date_filled}")

Number of rows with only 'Assembly Date' filled: 0


### Result:

In [2032]:
# rows_removed = train_data.shape[0] - X.shape[0]
# rows_removed_percentage = rows_removed / train_data.shape[0] * 100  

# features_removed = train_data.shape[1] - X.shape[1]
# features_removed_percentage = features_removed / train_data.shape[1] * 100 

# print(f"Rows removed: {rows_removed} ({rows_removed_percentage:.2f}%)")
# print(f"Features removed: {features_removed} ({features_removed_percentage:.2f}%)") 

### Independent and Dependent variables

In [2033]:
X = train_data.drop(columns=['Claim Injury Type'])
y = train_data['Claim Injury Type']


----

In [2034]:
y.isna().sum()

0

### Train and Validation Split

In [2035]:
# split the data into training and testing sets

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

#### OIICS Nature of Injury Description
Between all the complains this feature is never filled, so we can drop it

In [2036]:
# drop OIICS Nature of Injury Description
X_train = X_train.drop(columns=['OIICS Nature of Injury Description'])
X_val = X_val.drop(columns=['OIICS Nature of Injury Description'])
X_test = X_test.drop(columns=['OIICS Nature of Injury Description'])


----

## 3.1 Numerical Features Preprocessing

In [2037]:
# Step 1.
# Identifying Numerical features
numerical_features = X.select_dtypes(include=['number']).columns
numerical_features

Index(['Accident Date', 'Age at Injury', 'Assembly Date',
       'Average Weekly Wage', 'Birth Year', 'C-2 Date', 'C-3 Date',
       'First Hearing Date', 'IME-4 Count', 'Industry Code',
       'OIICS Nature of Injury Description', 'WCIO Cause of Injury Code',
       'WCIO Nature of Injury Code', 'WCIO Part Of Body Code',
       'Agreement Reached', 'Number of Dependents'],
      dtype='object')

In [2038]:
X[numerical_features].isna().sum()/df.shape[0]*100
# IME-4 count has a failry high NA percentage, but since the meaning of it could be usefull for later exploration I kept it. 
## Because IME-4 stands for "Independent Examiner's Report of Independent Medical Examination” 

# Other's have low scores, but instead of deleting them I will change them via either mean or median strategy. 
# Online I read if more than 60-70% is missing we drop the variable and we never try to fill in more than 5%. for now I filled in all via either mean or median. 
# But I could also drop some. I wanted to ask you guys about it. 

Accident Date                          0.621597
Age at Injury                          0.000000
Assembly Date                          0.000000
Average Weekly Wage                    4.827700
Birth Year                             0.621597
C-2 Date                               2.453363
C-3 Date                              65.172687
First Hearing Date                    71.314015
IME-4 Count                           74.346177
Industry Code                          1.677925
OIICS Nature of Injury Description    96.723513
WCIO Cause of Injury Code              2.635344
WCIO Nature of Injury Code             2.638208
WCIO Part Of Body Code                 2.878321
Agreement Reached                      0.000000
Number of Dependents                   0.000000
dtype: float64

In [2039]:
numerical_features = numerical_features.drop(
    [col for col in numerical_features if 'Code' in col or 'Description' in col]
)

numerical_features

Index(['Accident Date', 'Age at Injury', 'Assembly Date',
       'Average Weekly Wage', 'Birth Year', 'C-2 Date', 'C-3 Date',
       'First Hearing Date', 'IME-4 Count', 'Agreement Reached',
       'Number of Dependents'],
      dtype='object')

In [2040]:
preProcess_numerical_train = X_train[numerical_features].copy()
preProcess_numerical_val = X_val[numerical_features].copy()
preProcess_numerical_test = X_test[numerical_features.drop('Agreement Reached')].copy()

In [2041]:
preProcess_numerical_train[numerical_features].isna().sum()/df.shape[0]*100

Accident Date            0.498087
Age at Injury            0.000000
Assembly Date            0.000000
Average Weekly Wage      3.871461
Birth Year               0.498087
C-2 Date                 1.960500
C-3 Date                52.161774
First Hearing Date      57.067489
IME-4 Count             59.485973
Agreement Reached        0.000000
Number of Dependents     0.000000
dtype: float64

In [2042]:
# Than it is the decision to either drop the rest or to it the following way. 
impute_strategy = {
    'Number of Dependents': 'mean',  # Use mean and optionally round if whole numbers are needed
    'IME-4 Count': 'median',
    'Birth Year': 'mean',
    'Average Weekly Wage': 'median',
    'Age at Injury': 'median', 
    'Agreement Reached' : 'mode' # Binary, so mode is suitable
}

# Only we might need a predictive model which looks at all the NA's from features and predicts more the values? 
# Since Cause of Injury Code and Nature of Injury Code and Part of Body Code might be related. 

In [2043]:
# Loop through each column and apply the specified imputation method
for col, strategy in impute_strategy.items():
    if strategy == 'mean':
        # Apply the mean and round for "Number of Dependents" specifically
        if col == 'Number of Dependents':
            train_mean = preProcess_numerical_train[col].mean()
            preProcess_numerical_train[col].fillna(round(train_mean), inplace=True)
            preProcess_numerical_val[col].fillna(round(train_mean), inplace=True)
            preProcess_numerical_test[col].fillna(round(train_mean), inplace=True)
            
        else:
            train_mean = preProcess_numerical_train[col].mean()
            preProcess_numerical_train[col].fillna(round(train_mean), inplace=True)
            preProcess_numerical_val[col].fillna(round(train_mean), inplace=True)
            preProcess_numerical_test[col].fillna(round(train_mean), inplace=True)

    elif strategy == 'median':

        train_median = preProcess_numerical_train[col].median()
        preProcess_numerical_train[col].fillna(train_median, inplace=True)
        preProcess_numerical_val[col].fillna(train_median, inplace=True)
        preProcess_numerical_test[col].fillna(train_median, inplace=True)

    elif strategy == 'mode':
        train_mode = preProcess_numerical_train[col].mode()[0]
        preProcess_numerical_train[col].fillna(train_mode, inplace=True)  # Mode returns an array, use [0] to get the value
        preProcess_numerical_val[col].fillna(train_mode, inplace=True)
        
        if col != 'Agreement Reached':
            preProcess_numerical_test[col].fillna(train_mode, inplace=True)

C:\Users\isa\AppData\Local\Temp\ipykernel_24172\571016926.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  preProcess_numerical_train[col].fillna(round(train_mean), inplace=True)
C:\Users\isa\AppData\Local\Temp\ipykernel_24172\571016926.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as

In [2044]:
print(preProcess_numerical_train[numerical_features].isnull().sum())

Accident Date             2956
Age at Injury                0
Assembly Date                0
Average Weekly Wage          0
Birth Year                   0
C-2 Date                 11635
C-3 Date                309565
First Hearing Date      338679
IME-4 Count                  0
Agreement Reached            0
Number of Dependents         0
dtype: int64


## 3.2 Outliers Treatment

Only done on X_train

In [2045]:
from scipy.stats import zscore
import numpy as np

# Define a function to handle outliers based on each feature's characteristics
def handle_outliers(data, features):
    for col in features:
        if data[col].skew() > 1:  # Skewed distribution, use IQR
            Q1 = data[col].quantile(0.25)
            Q3 = data[col].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            # Clip the values outside the IQR range
            data[col] = data[col].clip(lower=lower_bound, upper=upper_bound)
            print(f"Outliers in {col} handled using IQR method. Bounds: ({lower_bound}, {upper_bound})")
        
        elif abs(data[col].skew()) <= 1:  # Symmetrical or normal distribution, use Z-score
            z_scores = zscore(data[col].dropna())  # Drop NaN for Z-score calculation
            outliers = data[(z_scores > 3) | (z_scores < -3)].index
            # Mark or handle outliers (e.g., setting to NaN or capping)
            data.loc[outliers, col] = np.nan  # Optionally, fill with NaN or use another method
            print(f"Outliers in {col} handled using Z-score method.")

In [2046]:

# Apply the function to numerical features
handle_outliers(preProcess_numerical_train, ['Age at Injury', 'Birth Year', 'IME-4 Count', 'Number of Dependents']) 

Outliers in Age at Injury handled using Z-score method.
Outliers in Birth Year handled using Z-score method.
Outliers in IME-4 Count handled using IQR method. Bounds: (2.0, 2.0)
Outliers in Number of Dependents handled using Z-score method.


In [2047]:
print(preProcess_numerical_train.isnull().sum())

Accident Date             2956
Age at Injury              276
Assembly Date                0
Average Weekly Wage          0
Birth Year                 941
C-2 Date                 11635
C-3 Date                309565
First Hearing Date      338679
IME-4 Count                  0
Agreement Reached            0
Number of Dependents         0
dtype: int64


### Result:

In [2048]:
features_imputed = X[numerical_features].isna().sum() - preProcess_numerical_train[numerical_features].isna().sum()

print(f'Numerical features imputed: {features_imputed.sum()}')

Numerical features imputed: 637769


In [2049]:
X_train[numerical_features] = preProcess_numerical_train[numerical_features]
X_val[numerical_features] = preProcess_numerical_val[numerical_features]
X_test[numerical_features.drop('Agreement Reached')] = preProcess_numerical_test[numerical_features.drop('Agreement Reached')]

## 3.3 Categorical Features Preprocessing

### Overlook of the features
This notebook will include pre processing of the following variables:
- Carrier Name 
- Attorney Representative
- OIICS Nature of Injury Description
- Industry Code
- Industry Code Description
- Medical Fee Region
- C-2 Date
- First Hearing Date
- WCIO Cause of Injury Description
- WCIO Cause of Injury Code
- WCIO Part of Body Code
- WCIO Part of Body Description
- WCIO Cause of Injury Code
- WCIO Cause of Injury Description
- WCIO Nature of Injury Description
- WCIO Nature of Injury Code

Since we dropped some rows in the previous section we should check again for the updated number of missing values for the features we are interest in

In [2050]:
target_features = ['Carrier Name', 'Attorney/Representative',
                   'Industry Code','Industry Code Description', 'Medical Fee Region', 'C-2 Date', 'First Hearing Date','WCIO Cause of Injury Code','WCIO Cause of Injury Description',
                   'WCIO Part Of Body Code','WCIO Part Of Body Description','WCIO Cause of Injury Description','WCIO Cause of Injury Code','WCIO Nature of Injury Description',]

In [2051]:
preProcess_categorical1_train = X_train.copy()
preProcess_categorical1_val = X_val.copy()
preProcess_categorical1_test = X_test.copy()

In [2052]:
preProcess_categorical1_train[target_features].isnull().sum()/X.shape[0]*100

Carrier Name                          0.000000
Attorney/Representative               0.000000
Industry Code                         1.389484
Industry Code Description             1.389484
Medical Fee Region                    0.000000
C-2 Date                              2.026912
First Hearing Date                   59.000638
WCIO Cause of Injury Code             2.176556
WCIO Cause of Injury Description      2.176556
WCIO Part Of Body Code                2.371147
WCIO Part Of Body Description         2.371147
WCIO Cause of Injury Description      2.176556
WCIO Cause of Injury Code             2.176556
WCIO Nature of Injury Description     2.179170
dtype: float64

The features _`Carrier Name`_,  _`Attorney/Representative`_ and _`Medical Fee Region`_ no longer have missing values. Let's look at the others

### First Hearing Date
This feature also has a high percentage of missing values. According to the provided information for this project, 'A blank date means the claim has not yet had a hearing held'. So we should create a label for the ones that hadn't had a hearing yet, we will simply call it 'N/A'

In [2053]:
# transform First Hearing Date into pd.datetime
preProcess_categorical1_train['First Hearing Date'] = pd.to_datetime(preProcess_categorical1_train['First Hearing Date'])
preProcess_categorical1_val['First Hearing Date'] = pd.to_datetime(preProcess_categorical1_val['First Hearing Date'])
preProcess_categorical1_test['First Hearing Date'] = pd.to_datetime(preProcess_categorical1_test['First Hearing Date'])

In [2054]:
# fill NA with 'N/A'
preProcess_categorical1_train['First Hearing Date'] = preProcess_categorical1_train['First Hearing Date'].fillna(0)
preProcess_categorical1_val['First Hearing Date'] = preProcess_categorical1_val['First Hearing Date'].fillna(0)
preProcess_categorical1_test['First Hearing Date'] = preProcess_categorical1_test['First Hearing Date'].fillna(0)

preProcess_categorical1_train['First Hearing Date'].isna().sum()

0

To assist in the information that this feature can provide we can create another feature called _`Has First Hearing Date`_ - a binary value that indicates if the user has had it's first hearing date

In [2055]:
# create Has First Hearing Date based on if is 'N/A' or not
preProcess_categorical1_train['Has First Hearing Date'] = preProcess_categorical1_train['First Hearing Date'].apply(lambda x: 0 if x == 'N/A' else 1)
preProcess_categorical1_val['Has First Hearing Date'] = preProcess_categorical1_val['First Hearing Date'].apply(lambda x: 0 if x == 'N/A' else 1)
preProcess_categorical1_test['Has First Hearing Date'] = preProcess_categorical1_test['First Hearing Date'].apply(lambda x: 0 if x == 'N/A' else 1)


In [2056]:
preProcess_categorical1_train['Has First Hearing Date'].value_counts()

Has First Hearing Date
1    459220
Name: count, dtype: int64

### C-2 Date
Here we can use the same approach filling the NaNs with N/A

In [2057]:
preProcess_categorical1_train['C-2 Date'].fillna(0, inplace=True)
preProcess_categorical1_val['C-2 Date'].fillna(0, inplace=True)
preProcess_categorical1_test['C-2 Date'].fillna(0, inplace=True)

C:\Users\isa\AppData\Local\Temp\ipykernel_24172\3584662500.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  preProcess_categorical1_train['C-2 Date'].fillna(0, inplace=True)
C:\Users\isa\AppData\Local\Temp\ipykernel_24172\3584662500.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a c

### Codes and Descriptions
This section will analyse data related to codes and their descriptions

In [2058]:
df_codes = preProcess_categorical1_train[[col for col in preProcess_categorical1_train.columns if 'Code' in col]]
df_codes.drop(columns=['Industry Code Description', 'Zip Code'], inplace=True)

df_description = preProcess_categorical1_train[[col for col in preProcess_categorical1_train.columns if 'Description' in col]]

C:\Users\isa\AppData\Local\Temp\ipykernel_24172\2876846187.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_codes.drop(columns=['Industry Code Description', 'Zip Code'], inplace=True)


In [2059]:
# ensure that all codes are objects
df_codes = df_codes.astype('object')

df_codes.describe()

Industry Code  WCIO Cause of Injury Code  WCIO Nature of Injury Code  \
count        451244.0                   446726.0                    446711.0   
unique           24.0                       77.0                        56.0   
top              62.0                       56.0                        52.0   
freq          91355.0                    37240.0                    122778.0   

        WCIO Part Of Body Code  
count                 445609.0  
unique                    57.0  
top                       42.0  
freq                   41395.0

In [2060]:
#check the order of the codes
df_codes.columns

Index(['Industry Code', 'WCIO Cause of Injury Code',
       'WCIO Nature of Injury Code', 'WCIO Part Of Body Code'],
      dtype='object')

In [2061]:
#check the order of the descriptions
df_description.columns

Index(['Industry Code Description', 'WCIO Cause of Injury Description',
       'WCIO Nature of Injury Description', 'WCIO Part Of Body Description'],
      dtype='object')

In [2062]:
def code_description_consistency(df, code_column, description_column):
    # Remove rows with missing values in either the code or description columns
    df_non_null = df.dropna(subset=[code_column, description_column])

    # Check if each code maps to a unique description
    code_consistency = df_non_null.groupby(code_column)[description_column].nunique() == 1

    # Check if each description maps to a unique code
    description_consistency = df_non_null.groupby(description_column)[code_column].nunique() == 1

    # Check overall consistency
    codes_match_descriptions = code_consistency.all()
    descriptions_match_codes = description_consistency.all()

    return codes_match_descriptions, descriptions_match_codes

In [2063]:
for code_col, desc_col in zip(df_codes.columns, df_description.columns):
    # Get the consistency check result
    result = code_description_consistency(preProcess_categorical1_train, code_col, desc_col)
    
    # Print the names of the columns along with the result
    print(f"Checking consistency between '{code_col}' and '{desc_col}': {result}")

Checking consistency between 'Industry Code' and 'Industry Code Description': (True, False)
Checking consistency between 'WCIO Cause of Injury Code' and 'WCIO Cause of Injury Description': (True, False)
Checking consistency between 'WCIO Nature of Injury Code' and 'WCIO Nature of Injury Description': (True, True)
Checking consistency between 'WCIO Part Of Body Code' and 'WCIO Part Of Body Description': (True, False)


So codes match the same description but the same does not happen for the description since we have the same description in different codes

In [2064]:
# for code_col, desc_col in zip(df_codes.columns, df_description.columns):    
#     code_column = code_col
#     description_column = desc_col

#     # Count occurrences of each code/description pair
#     code_description_counts = X_train.groupby([code_column, description_column]).size().reset_index(name='Count').sort_index()

#     # Plotting
#     plt.figure(figsize=(12, 8))
#     plt.bar(
#         x=code_description_counts[code_column].astype(str) + ' / ' + code_description_counts[description_column],
#         height=code_description_counts['Count'],
#         color='skyblue'
#     )

#     # Formatting the plot
#     plt.xlabel(f"{code_column} / {description_column}")
#     plt.ylabel("Frequency")
#     plt.title(f"Frequency of {code_column} and {description_column} Pairs")
#     plt.xticks(rotation=90)
#     plt.tight_layout()
#     plt.show()

We can use the mode to fill the missing values (copied out because already done)

In [2065]:
# def fill_missing_with_mode(df, columns):
#     """
#     Fill missing values in a code column with the most frequent code.
    
#     Parameters:
#     - df (pd.DataFrame): The DataFrame containing the data.
#     - code (str): The name of the column representing codes.
    
#     Returns:
#     - pd.DataFrame: The DataFrame with missing values in the code column filled.
#     """
#     # Find the most frequent code
#     for column in columns:
#         most_frequent_code = df[column].mode().iloc[0]  # Get the mode (most frequent value)
        
#         # Use .loc to avoid SettingWithCopyWarning and fill NaNs
#         df.loc[:, column] = df[column].fillna(most_frequent_code)
    
#     # Use .infer_objects to avoid FutureWarning if dtype downcasting is a concern
#     df = df.infer_objects(copy=False)
    
#     return df

In [2066]:
# codes_columns = df_codes.columns.tolist()
# description_columns = df_description.columns.tolist()

# # fill missing values in df_codes and df_description separately
# preProcess_categorical1 = fill_missing_with_mode(preProcess_categorical1, codes_columns)
# preProcess_categorical1 = fill_missing_with_mode(preProcess_categorical1, description_columns)

# # fill missing values for test data
# X_test = fill_missing_with_mode(X_test, codes_columns)
# X_test = fill_missing_with_mode(X_test, description_columns)

In [2067]:
def fill_missing_with_mode(df, columns):
    """
    Fill missing values in a code column with the most frequent code.
    
    Parameters:
    - df (pd.DataFrame): The DataFrame containing the data.
    - code (str): The name of the column representing codes.
    
    Returns:
    - pd.DataFrame: The DataFrame with missing values in the code column filled.
    """
    # Find the most frequent code
    for column in columns:
        most_frequent_code = df[column].mode().iloc[0]  # Get the mode (most frequent value)
        
        # Use .loc to avoid SettingWithCopyWarning and fill NaNs
        df.loc[:, column] = df[column].fillna(most_frequent_code)
    
    # Use .infer_objects to avoid FutureWarning if dtype downcasting is a concern
    df = df.infer_objects(copy=False)
    
    return df

In [2068]:
codes_columns = df_codes.columns.tolist()
description_columns = df_description.columns.tolist()

# fill missing values in df_codes and df_description separately
preProcess_categorical1_train = fill_missing_with_mode(preProcess_categorical1_train, codes_columns)
preProcess_categorical1_train = fill_missing_with_mode(preProcess_categorical1_train, description_columns)

# fill missing values for validation data
preProcess_categorical1_val = fill_missing_with_mode(preProcess_categorical1_val, codes_columns)
preProcess_categorical1_val = fill_missing_with_mode(preProcess_categorical1_val, description_columns)

# fill missing values for test data
preProcess_categorical1_test = fill_missing_with_mode(preProcess_categorical1_test, codes_columns)
preProcess_categorical1_test = fill_missing_with_mode(preProcess_categorical1_test, description_columns)

### Results Cat 1:

In [2069]:


features_imputed = X[target_features].isna().sum() - preProcess_categorical1_train[target_features].isna().sum()
print(f'Categorical features imputed: {features_imputed.sum()}')

print(preProcess_categorical1_train[target_features].isna().sum())

Categorical features imputed: 570085
Carrier Name                         0
Attorney/Representative              0
Industry Code                        0
Industry Code Description            0
Medical Fee Region                   0
C-2 Date                             0
First Hearing Date                   0
WCIO Cause of Injury Code            0
WCIO Cause of Injury Description     0
WCIO Part Of Body Code               0
WCIO Part Of Body Description        0
WCIO Cause of Injury Description     0
WCIO Cause of Injury Code            0
WCIO Nature of Injury Description    0
dtype: int64


In [2070]:
X_train = preProcess_categorical1_train

X_val = preProcess_categorical1_val

X_test = preProcess_categorical1_test

## Preprocessing Catergorical 2:

#### preprocessing categorical data

In [2071]:
list_column_analyze = ['Carrier Type'
                       ,'Gender'
                       ,'COVID-19 Indicator'
                       ,'C-3 Date'
                       ,'WCIO Nature of Injury Code'
                       ,'Alternative Dispute Resolution'
                       ,'Zip Code'
                       ,'County of Injury'
                       ,'Accident Date'
                       ,'District Name'
                       ,'Assembly Date']

preProcess_categorical2_train = X_train[list_column_analyze].copy()
preProcess_categorical2_val = X_val[list_column_analyze].copy()
preProcess_categorical2_test = X_test[list_column_analyze].copy()
# # put every column that are object to higher case to ensure data consistency and avoid duplicates
# preProcess_categorical2.loc[:, preProcess_categorical2.select_dtypes(include=['object']).columns] = \
#     preProcess_categorical2.select_dtypes(include=['object']).apply(lambda x: x.str.upper())

In [2072]:
# reset index otherwise with the groupby the index will be lost
preProcess_categorical2_train = preProcess_categorical2_train.reset_index()
preProcess_categorical2_val = preProcess_categorical2_val.reset_index()
preProcess_categorical2_test = preProcess_categorical2_test.reset_index()


In [2073]:
preProcess_categorical2_train.describe(include= 'object').T

count unique          top    freq
Carrier Type                    459220      8  1A. PRIVATE  228421
Gender                          459220      4            M  268208
COVID-19 Indicator              459220      2            N  437151
Alternative Dispute Resolution  459220      3            N  457133
Zip Code                        436392   9143        11236    2646
County of Injury                459220     63      SUFFOLK   48379
District Name                   459220      8          NYC  216838

In [2074]:
# calculate the mode for each combination of County of Injury and District Name and also for District Name
# create table with mode values for Zip Code

mode_zip_codes_train = preProcess_categorical2_train.groupby(['County of Injury', 'District Name'])['Zip Code'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
mode_zip_district_train = preProcess_categorical2_train.groupby('District Name')['Zip Code'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None).reset_index()
mode_zip_district_train.columns = ['District Name', 'Zip Code_mode_district']


for dataset in [preProcess_categorical2_test, preProcess_categorical2_val, preProcess_categorical2_train]:
    # Merge with mode_zip_codes based on County of Injury and District Name
    dataset = dataset.merge(
        mode_zip_codes_train.reset_index(),
        on=['County of Injury', 'District Name'],
        how='left',
        suffixes=('', '_mode')
    )

    # Fill missing Zip Code values with the mode values from preProcess_categorical2_train
    dataset['Zip Code'] = dataset['Zip Code'].combine_first(dataset['Zip Code_mode'])

    # Merge with mode_zip_district for District Name fallback
    dataset = dataset.merge(
        mode_zip_district_train,
        on='District Name',
        how='left'
    )

    # Fill remaining missing Zip Code values with District Name mode
    dataset['Zip Code'] = dataset['Zip Code'].combine_first(dataset['Zip Code_mode_district'])

    # drop the added columns
    dataset.drop(columns=['Zip Code_mode', 'Zip Code_mode_district'], inplace=True)

# Check for any remaining missing values in Zip Code for preProcess_categorical2_test and preProcess_categorical2_val
print("Missing Zip Code values in x_test:", preProcess_categorical2_test['Zip Code'].isnull().sum())
print("Missing Zip Code values in preProcess_categorical2_val:", preProcess_categorical2_val['Zip Code'].isnull().sum())
print("Missing Zip Code values in preProcess_categorical2_val:", preProcess_categorical2_train['Zip Code'].isnull().sum())


C:\Users\isa\AppData\Local\Temp\ipykernel_24172\2803347120.py:4: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'float'
  mode_zip_codes_train = preProcess_categorical2_train.groupby(['County of Injury', 'District Name'])['Zip Code'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
C:\Users\isa\AppData\Local\Temp\ipykernel_24172\2803347120.py:4: UserWarning: Unable to sort modes: '<' not supported between instances of 'float' and 'str'
  mode_zip_codes_train = preProcess_categorical2_train.groupby(['County of Injury', 'District Name'])['Zip Code'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)


Missing Zip Code values in x_test: 19342
Missing Zip Code values in preProcess_categorical2_val: 5809
Missing Zip Code values in preProcess_categorical2_val: 22828


In [2075]:
mean_accident_date = preProcess_categorical2_train['Accident Date'].mean()

# Fill NaN values in 'accident_date' with the calculated mean date for each set
preProcess_categorical2_train['Accident Date'].fillna(mean_accident_date, inplace=True)
preProcess_categorical2_val['Accident Date'].fillna(mean_accident_date, inplace=True)
preProcess_categorical2_test['Accident Date'].fillna(mean_accident_date, inplace=True)

C:\Users\isa\AppData\Local\Temp\ipykernel_24172\3321654992.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  preProcess_categorical2_train['Accident Date'].fillna(mean_accident_date, inplace=True)
C:\Users\isa\AppData\Local\Temp\ipykernel_24172\3321654992.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values

In [2076]:
preProcess_categorical2_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 459220 entries, 0 to 459219
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   Claim Identifier                459220 non-null  int64  
 1   Carrier Type                    459220 non-null  object 
 2   Gender                          459220 non-null  object 
 3   COVID-19 Indicator              459220 non-null  object 
 4   C-3 Date                        149655 non-null  float64
 5   WCIO Nature of Injury Code      459220 non-null  float64
 6   Alternative Dispute Resolution  459220 non-null  object 
 7   Zip Code                        436392 non-null  object 
 8   County of Injury                459220 non-null  object 
 9   Accident Date                   459220 non-null  float64
 10  District Name                   459220 non-null  object 
 11  Assembly Date                   459220 non-null  float64
dtypes: float64(4), i

In [2077]:
preProcess_categorical2_train.describe().T

count          mean           std  \
Claim Identifier            459220.0  5.778956e+06  2.224024e+05   
C-3 Date                    149655.0  1.627336e+09  2.836561e+07   
WCIO Nature of Injury Code  459220.0  4.133435e+01  2.197612e+01   
Accident Date               459220.0  1.619633e+09  5.887235e+07   
Assembly Date               459220.0  1.626720e+09  2.721536e+07   

                                     min           25%           50%  \
Claim Identifier            5.393066e+06  5.586662e+06  5.778242e+06   
C-3 Date                    7.216128e+08  1.603757e+09  1.626826e+09   
WCIO Nature of Injury Code  1.000000e+00  2.500000e+01  4.900000e+01   
Accident Date              -2.625696e+08  1.600214e+09  1.624406e+09   
Assembly Date               1.577837e+09  1.603757e+09  1.627603e+09   

                                     75%           max  
Claim Identifier            5.971532e+06  6.165685e+06  
C-3 Date                    1.650413e+09  1.717114e+09  
WCIO Nature of Injury Code  5.200000e+01  9.100000e+01  
Accident Date               1.647648e+09  1.694390e+09  
Assembly Date               1.650413e+09  1.672445e+09

In [2078]:
preProcess_categorical2_train[['C-3 Date', 'Assembly Date', 'Accident Date']].isna().sum()

C-3 Date         309565
Assembly Date         0
Accident Date         0
dtype: int64

In [2079]:
# add the index back to be able to commit the changes
preProcess_categorical2_train.set_index('Claim Identifier', inplace=True)
preProcess_categorical2_val.set_index('Claim Identifier', inplace=True)
preProcess_categorical2_test.set_index('Claim Identifier', inplace=True)

### Result:

In [2080]:
features_imputed = X_train[list_column_analyze].isna().sum() - preProcess_categorical2_train[list_column_analyze].isna().sum()

print(X[list_column_analyze].isna().sum())
print(preProcess_categorical2_train[list_column_analyze].isna().sum())

print(f'Categorical features imputed: {features_imputed.sum()}')

Carrier Type                           0
Gender                                 0
COVID-19 Indicator                     0
C-3 Date                          386781
WCIO Nature of Injury Code         15657
Alternative Dispute Resolution         0
Zip Code                           28637
County of Injury                       0
Accident Date                       3689
District Name                          0
Assembly Date                          0
dtype: int64
Carrier Type                           0
Gender                                 0
COVID-19 Indicator                     0
C-3 Date                          309565
WCIO Nature of Injury Code             0
Alternative Dispute Resolution         0
Zip Code                           22828
County of Injury                       0
Accident Date                          0
District Name                          0
Assembly Date                          0
dtype: int64
Categorical features imputed: 2956


In [2081]:
X_train[list_column_analyze] = preProcess_categorical2_train[list_column_analyze]
X_val[list_column_analyze] = preProcess_categorical2_val[list_column_analyze]
X_test[list_column_analyze] = preProcess_categorical2_test[list_column_analyze]

X_train.isna().sum()

Accident Date                             0
Age at Injury                           276
Alternative Dispute Resolution            0
Assembly Date                             0
Attorney/Representative                   0
Average Weekly Wage                       0
Birth Year                              941
C-2 Date                                  0
C-3 Date                             309565
Carrier Name                              0
Carrier Type                              0
County of Injury                          0
COVID-19 Indicator                        0
District Name                             0
First Hearing Date                        0
Gender                                    0
IME-4 Count                               0
Industry Code                             0
Industry Code Description                 0
Medical Fee Region                        0
WCIO Cause of Injury Code                 0
WCIO Cause of Injury Description          0
WCIO Nature of Injury Code      

# REMOVE THIS WHEN PRE PROCESSING IS CORRECT please :)

In [2082]:

X_train.fillna(0, inplace=True)
X_val.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

## Export clean data

In [2083]:
# X_train.to_csv('X_train_cleaned.csv')
# X_val.to_csv('X_val_cleaned.csv')
# X_test.to_csv('X_test_cleaned.csv')
# y_val.to_csv('y_val.csv')
#y_train.to_csv('y_train_cleaned.csv')

## 3.4 Data Scaling (Numerical)

In [2084]:
#imported here for demonstrative purposes but it is a good practice to import everything at the start.

X_train_num = X_train.loc[:, ['Age at Injury', 'Birth Year', 'IME-4 Count', 'Number of Dependents']]
X_val_num = X_val.loc[:, ['Age at Injury', 'Birth Year', 'IME-4 Count', 'Number of Dependents']]
X_test_num = X_test.loc[:, ['Age at Injury', 'Birth Year', 'IME-4 Count', 'Number of Dependents']]

#call function
scaler = MinMaxScaler()

#fit to training data
scaler.fit(X_train_num)

#transform the data
X_train_num_scaled = scaler.transform(X_train_num) # this will return an array
X_val_num_scaled = scaler.transform(X_val_num)
X_test_num_scaled = scaler.transform(X_test_num)

#show results
X_train_num_scaled

array([[0.58333333, 0.97623762, 0.        , 1.        ],
       [0.66666667, 0.97326733, 0.        , 0.83333333],
       [0.57142857, 0.97722772, 0.        , 0.33333333],
       ...,
       [0.67857143, 0.97227723, 0.        , 0.83333333],
       [0.        , 0.97920792, 0.        , 0.66666667],
       [0.30952381, 0.98811881, 0.        , 0.33333333]])

In [2085]:
X_train_num_scaled = pd.DataFrame(X_train_num_scaled, columns = X_train_num.columns).set_index(X_train.index)
X_val_num_scaled = pd.DataFrame(X_val_num_scaled, columns = X_val_num.columns).set_index(X_val.index)
X_test_num_scaled = pd.DataFrame(X_test_num_scaled, columns = X_test_num.columns).set_index(X_test.index)

In [2086]:

X_train[['Age at Injury', 'Birth Year', 'IME-4 Count', 'Number of Dependents']] = X_train_num_scaled
X_val[['Age at Injury', 'Birth Year', 'IME-4 Count', 'Number of Dependents']] = X_val_num_scaled
X_test[['Age at Injury', 'Birth Year', 'IME-4 Count', 'Number of Dependents']] = X_test_num_scaled

### Scaling Timestamp

In [2087]:
# columns that contain Date in the name
date_cols = X_train.columns[X_train.columns.str.contains('Date')]
date_cols = date_cols.drop('Has First Hearing Date')
date_cols = date_cols.drop('First Hearing Date')

date_cols

Index(['Accident Date', 'Assembly Date', 'C-2 Date', 'C-3 Date'], dtype='object')

In [2088]:
X_train_time_scaling = X_train[date_cols].copy()
X_val_time_scaling = X_val[date_cols].copy()
X_test_time_scaling = X_test[date_cols].copy()

In [2089]:
X_train_time_scaling.head()

Accident Date  Assembly Date      C-2 Date      C-3 Date
Claim Identifier                                                          
5785935            1.628122e+09   1.628554e+09  1.628554e+09  1.630282e+09
6090033            1.663114e+09   1.663718e+09  1.663718e+09  1.664237e+09
6136197            1.667779e+09   1.668730e+09  1.668730e+09  0.000000e+00
6019545            1.599005e+09   1.655770e+09  1.655770e+09  1.647389e+09
5792247            1.628813e+09   1.629245e+09  1.629245e+09  1.638230e+09

In [2090]:
def safe_time_scaling(x):
    # Check if x is a datetime-like value and not equal to the minimum value
    if hasattr(x, 'dt') and not (x - x.min()).dt.total_seconds().eq(0).all():
        return (x - x.min()).dt.total_seconds() / (60 * 60 * 24)
    return x  # Skip transformation if it doesn't meet conditions

X_train_time_scaling = X_train_time_scaling.apply(safe_time_scaling)
X_val_time_scaling = X_val_time_scaling.apply(safe_time_scaling)
X_test_time_scaling = X_test_time_scaling.apply(safe_time_scaling)

X_train_time_scaling.head()

Accident Date  Assembly Date      C-2 Date      C-3 Date
Claim Identifier                                                          
5785935            1.628122e+09   1.628554e+09  1.628554e+09  1.630282e+09
6090033            1.663114e+09   1.663718e+09  1.663718e+09  1.664237e+09
6136197            1.667779e+09   1.668730e+09  1.668730e+09  0.000000e+00
6019545            1.599005e+09   1.655770e+09  1.655770e+09  1.647389e+09
5792247            1.628813e+09   1.629245e+09  1.629245e+09  1.638230e+09

In [2091]:
scaler = StandardScaler()
scaler.fit(X_train_time_scaling) 

StandardScaler()

In [2092]:
X_train_scaled = scaler.transform(X_train_time_scaling)
X_val_scaled = scaler.transform(X_val_time_scaling)
X_test_scaled = scaler.transform(X_test_time_scaling)

In [2093]:
#transform the data
X_train_time_scaled = scaler.transform(X_train_time_scaling)
X_val_time_scaled = scaler.transform(X_val_time_scaling)
X_test_time_scaled = scaler.transform(X_test_time_scaling)


In [2094]:
# put the data back into a dataframe
X_train_time_scaled = pd.DataFrame(X_train_time_scaled, columns = X_train_time_scaling.columns).set_index(X_train.index)
X_val_time_scaled = pd.DataFrame(X_val_time_scaled, columns = X_val_time_scaling.columns).set_index(X_val.index)
X_test_time_scaled = pd.DataFrame(X_test_time_scaled, columns = X_test_time_scaling.columns).set_index(X_test.index)

In [2095]:
X_train[date_cols] = X_train_time_scaled
X_val[date_cols] = X_val_time_scaled
X_test[date_cols] = X_test_time_scaled

In [2096]:
X_train.head()

Accident Date  Age at Injury Alternative Dispute Resolution  \
Claim Identifier                                                                
5785935                0.144191       0.583333                              N   
6090033                0.738563       0.666667                              N   
6136197                0.817812       0.571429                              N   
6019545               -0.350384       0.654762                              N   
5792247                0.155932       0.630952                              N   

                  Assembly Date Attorney/Representative  Average Weekly Wage  \
Claim Identifier                                                               
5785935                0.067364                       Y               744.06   
6090033                1.359460                       Y               845.29   
6136197                1.543591                       N                 0.00   
6019545                1.067389                       N                 0.00   
5792247                0.092762                       Y               668.08   

                  Birth Year  C-2 Date  C-3 Date                Carrier Name  \
Claim Identifier                                                               
5785935             0.976238  0.167876  1.441774       PROPERTY AND CASUALTY   
6090033             0.973267  0.304202  1.486281   EVEREST PREMIER INSURANCE   
6136197             0.977228  0.323629 -0.695139     CHARTER OAK FIRE INS CO   
6019545             0.972772  0.273386  1.464197  NEW HAMPSHIRE INSURANCE CO   
5792247             0.974257  0.170556  1.452193        STATE INSURANCE FUND   

                 Carrier Type County of Injury COVID-19 Indicator  \
Claim Identifier                                                    
5785935           1A. PRIVATE           QUEENS                  N   
6090033           1A. PRIVATE           QUEENS                  N   
6136197           1A. PRIVATE         ROCKLAND                  N   
6019545           1A. PRIVATE      WESTCHESTER                  N   
5792247               2A. SIF           ALBANY                  N   

                 District Name             First Hearing Date Gender  \
Claim Identifier                                                       
5785935                    NYC                              0      F   
6090033                    NYC  1970-01-01 00:00:01.684195200      M   
6136197                    NYC                              0      M   
6019545                    NYC                              0      M   
5792247                 ALBANY     1970-01-01 00:00:01.695600      F   

                  IME-4 Count  Industry Code       Industry Code Description  \
Claim Identifier                                                               
5785935                   0.0           31.0                   MANUFACTURING   
6090033                   0.0           48.0  TRANSPORTATION AND WAREHOUSING   
6136197                   0.0           48.0  TRANSPORTATION AND WAREHOUSING   
6019545                   0.0           23.0                    CONSTRUCTION   
5792247                   0.0           44.0                    RETAIL TRADE   

                 Medical Fee Region  WCIO Cause of Injury Code  \
Claim Identifier                                                 
5785935                          IV                       29.0   
6090033                          IV                       45.0   
6136197                         III                       68.0   
6019545                          UK                       60.0   
5792247                           I                       29.0   

                             WCIO Cause of Injury Description  \
Claim Identifier                                                
5785935                                         ON SAME LEVEL   
6090033           COLLISION OR SIDESWIPE WITH ANOTHER VEHICLE   
6136197                                     STATIONARY 

## 3.5 Encoding

In [2097]:
X_train_encoded = X_train.copy()
X_val_encoded = X_val.copy()
X_test_encoded = X_test.copy()

y_train_encoded = y_train.copy()
y_val_encoded = y_val.copy()

Change all Codes to Strings

In [2098]:
# Print data types before the change
print("Data types before change:")
categorical = X_train_encoded.select_dtypes(include=['object']).columns.tolist()
print(categorical)

# Identify columns that end with "Code"
code_columns = [col for col in X_train_encoded.columns if col.endswith("Code")]

# Convert these columns to strings without altering values
X_train_encoded[code_columns] = X_train_encoded[code_columns].astype(str)
X_val_encoded[code_columns] = X_val_encoded[code_columns].astype(str)
X_test_encoded[code_columns] = X_test_encoded[code_columns].astype(str)

# Print data types after the change
print("\nData types after change:")
print(X_train_encoded.dtypes)

Data types before change:
['Alternative Dispute Resolution', 'Attorney/Representative', 'Carrier Name', 'Carrier Type', 'County of Injury', 'COVID-19 Indicator', 'District Name', 'First Hearing Date', 'Gender', 'Industry Code Description', 'Medical Fee Region', 'WCIO Cause of Injury Description', 'WCIO Nature of Injury Description', 'WCIO Part Of Body Description', 'Zip Code', 'WCB Decision']

Data types after change:
Accident Date                        float64
Age at Injury                        float64
Alternative Dispute Resolution        object
Assembly Date                        float64
Attorney/Representative               object
Average Weekly Wage                  float64
Birth Year                           float64
C-2 Date                             float64
C-3 Date                             float64
Carrier Name                          object
Carrier Type                          object
County of Injury                      object
COVID-19 Indicator                    

In [2099]:
categorical = X_train_encoded.select_dtypes(include=['object']).columns.tolist()
categorical

['Alternative Dispute Resolution',
 'Attorney/Representative',
 'Carrier Name',
 'Carrier Type',
 'County of Injury',
 'COVID-19 Indicator',
 'District Name',
 'First Hearing Date',
 'Gender',
 'Industry Code',
 'Industry Code Description',
 'Medical Fee Region',
 'WCIO Cause of Injury Code',
 'WCIO Cause of Injury Description',
 'WCIO Nature of Injury Code',
 'WCIO Nature of Injury Description',
 'WCIO Part Of Body Code',
 'WCIO Part Of Body Description',
 'Zip Code',
 'WCB Decision']

In [2100]:
categorical_features = [col for col in categorical 
    if 'Date' not in col and 'Year' not in col and 'Description' not in col
]
categorical_features = categorical_features

In [2101]:
enc1 = OneHotEncoder(handle_unknown= 'ignore', sparse_output=False, drop='first')  # 'drop=first' to avoid multicollinearity
enc2 = LabelEncoder() #encoder for labels

Splitting into low and high-cardinlity because of memory errors using OneHotEncoding for high-cardinality features e.g Carrier Name, Zip code

In [2102]:
print(X_val.columns)

Index(['Accident Date', 'Age at Injury', 'Alternative Dispute Resolution',
       'Assembly Date', 'Attorney/Representative', 'Average Weekly Wage',
       'Birth Year', 'C-2 Date', 'C-3 Date', 'Carrier Name', 'Carrier Type',
       'County of Injury', 'COVID-19 Indicator', 'District Name',
       'First Hearing Date', 'Gender', 'IME-4 Count', 'Industry Code',
       'Industry Code Description', 'Medical Fee Region',
       'WCIO Cause of Injury Code', 'WCIO Cause of Injury Description',
       'WCIO Nature of Injury Code', 'WCIO Nature of Injury Description',
       'WCIO Part Of Body Code', 'WCIO Part Of Body Description', 'Zip Code',
       'Agreement Reached', 'WCB Decision', 'Number of Dependents',
       'Has First Hearing Date'],
      dtype='object')


In [2103]:
# Select columns with low cardinality for one-hot encoding
low_cardinality_cols = [col for col in categorical_features if X_train_encoded[col].nunique() < 10]

print(low_cardinality_cols)
# Fit the encoder on X_train_encoded
enc1.fit(X_train_encoded[low_cardinality_cols])

# Transform X_train_encoded
encoded_low_cardinality_train = enc1.transform(X_train_encoded[low_cardinality_cols])

# Convert to DataFrame for X_train_encoded
encoded_df_train = pd.DataFrame(encoded_low_cardinality_train, 
                                columns=enc1.get_feature_names_out(low_cardinality_cols), 
                                index=X_train_encoded.index)

# Transform X_val and X_test using the already-fitted encoder
encoded_low_cardinality_val = enc1.transform(X_val[low_cardinality_cols])
encoded_df_val = pd.DataFrame(encoded_low_cardinality_val, 
                              columns=enc1.get_feature_names_out(low_cardinality_cols), 
                              index=X_val.index)
# encoded_low_cardinality_test = enc1.transform(X_test[low_cardinality_cols])
# encoded_df_test = pd.DataFrame(encoded_low_cardinality_test, 
#                                columns=enc1.get_feature_names_out(low_cardinality_cols), 
#                                index=X_test.index)

# Drop original low-cardinality columns and concatenate the one-hot encoded columns
X_train_encoded = X_train_encoded.drop(columns=low_cardinality_cols)
X_train_encoded = pd.concat([X_train_encoded, encoded_df_train], axis=1)

X_val_encoded = X_val.drop(columns=low_cardinality_cols)
X_val_encoded = pd.concat([X_val_encoded, encoded_df_val], axis=1)

# X_test_encoded = X_test.drop(columns=low_cardinality_cols)
# X_test_encoded = pd.concat([X_test_encoded, encoded_df_test], axis=1)


['Alternative Dispute Resolution', 'Attorney/Representative', 'Carrier Type', 'COVID-19 Indicator', 'District Name', 'Gender', 'Medical Fee Region', 'WCB Decision']


In [2104]:
# Identify high-cardinality columns for frequency encoding that exist in X_train_encoded
high_cardinality_cols = [col for col in categorical_features if col in X_train_encoded.columns and X_train_encoded[col].nunique() >= 10]

# Apply frequency encoding to high-cardinality columns in X_train, X_val, and X_test
for col in high_cardinality_cols:
    # Calculate the frequency map from the training set
    frequency_map = X_train_encoded[col].value_counts(normalize=True)
    
    # Apply the frequency map to the training set
    X_train_encoded[col] = X_train_encoded[col].map(frequency_map)
    
    # Apply the frequency map to the validation set, filling unseen categories with 0 or a default value
    X_val[col] = X_val[col].map(frequency_map).fillna(0)
    
    # Apply the frequency map to the test set, filling unseen categories with 0 or a default value
    X_test[col] = X_test[col].map(frequency_map).fillna(0)


In [2105]:
X_train_encoded.head().T

Claim Identifier                                                             5785935  \
Accident Date                                                               0.144191   
Age at Injury                                                               0.583333   
Assembly Date                                                               0.067364   
Average Weekly Wage                                                           744.06   
Birth Year                                                                  0.976238   
C-2 Date                                                                    0.167876   
C-3 Date                                                                    1.441774   
Carrier Name                                                                0.003846   
County of Injury                                                            0.101546   
First Hearing Date                                                                 0   
IME-4 Count                                                                      0.0   
Industry Code                                                               0.017623   
Industry Code Description                                              MANUFACTURING   
WCIO Cause of Injury Code                                                   0.051032   
WCIO Cause of Injury Description                                       ON SAME LEVEL   
WCIO Nature of Injury Code                                                   0.06304   
WCIO Nature of Injury Description                   ALL OTHER SPECIFIC INJURIES, NOC   
WCIO Part Of Body Code                                                      0.119781   
WCIO Part Of Body Description                                        LOWER BACK AREA   
Zip Code                                                                     0.00211   
Agreement Reached                                                                0.0   
Number of Dependents                                                             1.0   
Has First Hearing Date                                                             1   
Alternative Dispute Resolution_U                                                 0.0   
Alternative Dispute Resolution_Y                                                 0.0   
Attorney/Representative_Y                                                        1.0   
Carrier Type_2A. SIF                                                             0.0   
Carrier Type_3A. SELF PUBLIC                                                     0.0   
Carrier Type_4A. SELF PRIVATE                                                    0.0   
Carrier Type_5A. SPECIAL FUND - CONS. COMM. (SE...                               0.0   
Carrier Type_5C. SPECIAL FUND - POI CARRIER WCB...                               0.0   
Carrier Type_5D. SPECIAL FUND - UNKNOWN                                          0.0   
Carrier Type_UNKNOWN                                                             0.0   
COVID-19 Indicator_Y                                                             0.0   
District Name_BINGHAMTON                                                         0.0   
District Name_BUFFALO                                                            0.0   
District Name_HAUPPAUGE                                                          0.0   
District Name_NYC                                                                1.0   
District Name_ROCHESTER                                                          0.0   
District Name_STATEWIDE                                                          0.0   
District Name_SYRACUSE                                                           0.0   
Gender_M                                                                         0.0   
Gender_U                                                                         0.0   
Gender_X                                                                         0.0   
Medical Fee Region_II                   

Encoding Target variable

In [2106]:
enc2.fit(y_train_encoded)

y_train_encoded = enc2.transform(y_train_encoded)
y_val_encoded = enc2.transform(y_val_encoded)

Now we have encoded in a diferent df but i dont know how to encode them directly in the x_train without encoding things we dont want

In [2107]:
X_train_encoded.head().T

Claim Identifier                                                             5785935  \
Accident Date                                                               0.144191   
Age at Injury                                                               0.583333   
Assembly Date                                                               0.067364   
Average Weekly Wage                                                           744.06   
Birth Year                                                                  0.976238   
C-2 Date                                                                    0.167876   
C-3 Date                                                                    1.441774   
Carrier Name                                                                0.003846   
County of Injury                                                            0.101546   
First Hearing Date                                                                 0   
IME-4 Count                                                                      0.0   
Industry Code                                                               0.017623   
Industry Code Description                                              MANUFACTURING   
WCIO Cause of Injury Code                                                   0.051032   
WCIO Cause of Injury Description                                       ON SAME LEVEL   
WCIO Nature of Injury Code                                                   0.06304   
WCIO Nature of Injury Description                   ALL OTHER SPECIFIC INJURIES, NOC   
WCIO Part Of Body Code                                                      0.119781   
WCIO Part Of Body Description                                        LOWER BACK AREA   
Zip Code                                                                     0.00211   
Agreement Reached                                                                0.0   
Number of Dependents                                                             1.0   
Has First Hearing Date                                                             1   
Alternative Dispute Resolution_U                                                 0.0   
Alternative Dispute Resolution_Y                                                 0.0   
Attorney/Representative_Y                                                        1.0   
Carrier Type_2A. SIF                                                             0.0   
Carrier Type_3A. SELF PUBLIC                                                     0.0   
Carrier Type_4A. SELF PRIVATE                                                    0.0   
Carrier Type_5A. SPECIAL FUND - CONS. COMM. (SE...                               0.0   
Carrier Type_5C. SPECIAL FUND - POI CARRIER WCB...                               0.0   
Carrier Type_5D. SPECIAL FUND - UNKNOWN                                          0.0   
Carrier Type_UNKNOWN                                                             0.0   
COVID-19 Indicator_Y                                                             0.0   
District Name_BINGHAMTON                                                         0.0   
District Name_BUFFALO                                                            0.0   
District Name_HAUPPAUGE                                                          0.0   
District Name_NYC                                                                1.0   
District Name_ROCHESTER                                                          0.0   
District Name_STATEWIDE                                                          0.0   
District Name_SYRACUSE                                                           0.0   
Gender_M                                                                         0.0   
Gender_U                                                                         0.0   
Gender_X                                                                         0.0   
Medical Fee Region_II                   

## Export scaled and encoding data

In [2108]:
# X_train_encoded.to_csv('X_train_encoded.csv')
# pd.DataFrame(y_train_encoded).to_csv('y_train_encoded.csv')
# X_val_encoded.to_csv('X_val_encoded.csv')
# pd.DataFrame(y_val_encoded).to_csv('y_val_encoded.csv')

## Drop Description Columns (NEEDS TO BE MOVED!!)

In [ ]:
# List of columns to drop
desc_cols = ['Industry Code Description', 'WCIO Cause of Injury Description', 
             'WCIO Nature of Injury Description', 'WCIO Part Of Body Description',]

# Drop these columns in X_train_encoded, X_val, and X_test
X_train_encoded = X_train_encoded.drop(columns=desc_cols)

KeyError: "['Industry Code Description', 'WCIO Cause of Injury Description', 'WCIO Nature of Injury Description', 'WCIO Part Of Body Description'] not found in axis"

## RFE with Random Forest

Random Sample from the data set

In [2110]:
# Take a random sample of 5000 rows from X_train_encoded and y_train_encoded
X_train_sample = X_train_encoded.sample(n=5000, random_state=42)
y_train_sample = y_train.loc[X_train_sample.index]

In [2111]:
# Convert 'First Hearing Date' to timestamps, setting invalid entries to NaT
X_train_sample['First Hearing Date'] = pd.to_datetime(X_train_sample['First Hearing Date'], errors='coerce')
X_train_sample['First Hearing Date'] = X_train_sample['First Hearing Date'].apply(lambda x: x.timestamp() if pd.notnull(x) else np.nan)

In [2112]:
# Identify columns with 'Date' in their name
date_columns = [col for col in X_train_sample.columns if 'Date' in col]

# Check data types of each date column
for col in date_columns:
    print(f"Data type of '{col}' column:", X_train_sample[col].dtype)



Data type of 'Accident Date' column: float64
Data type of 'Assembly Date' column: float64
Data type of 'C-2 Date' column: float64
Data type of 'C-3 Date' column: float64
Data type of 'First Hearing Date' column: float64
Data type of 'Has First Hearing Date' column: int64


### RFECV

commented out for runtime

In [2122]:
X_train_encoded.drop(columns=['First Hearing Date'], inplace=True)

Accident Date  Age at Injury  Assembly Date  \
Claim Identifier                                                
5785935                0.144191       0.583333       0.067364   
6090033                0.738563       0.666667       1.359460   
6136197                0.817812       0.571429       1.543591   
6019545               -0.350384       0.654762       1.067389   
5792247                0.155932       0.630952       0.092762   

                  Average Weekly Wage  Birth Year  C-2 Date  C-3 Date  \
Claim Identifier                                                        
5785935                        744.06    0.976238  0.167876  1.441774   
6090033                        845.29    0.973267  0.304202  1.486281   
6136197                          0.00    0.977228  0.323629 -0.695139   
6019545                          0.00    0.972772  0.273386  1.464197   
5792247                        668.08    0.974257  0.170556  1.452193   

                  Carrier Name  County of Injury  IME-4 Count  Industry Code  \
Claim Identifier                                                               
5785935               0.003846          0.101546          0.0       0.017623   
6090033               0.000825          0.101546          0.0       0.065049   
6136197               0.029792          0.015914          0.0       0.065049   
6019545               0.022259          0.044920          0.0       0.053748   
5792247               0.193350          0.023838          0.0       0.075874   

                  WCIO Cause of Injury Code  WCIO Nature of Injury Code  \
Claim Identifier                                                          
5785935                            0.051032                    0.063040   
6090033                            0.029082                    0.294602   
6136197                            0.018939                    0.192385   
6019545                            0.057702                    0.004880   
5792247                            0.051032                    0.192385   

                  WCIO Part Of Body Code  Zip Code  Agreement Reached  \
Claim Identifier                                                        
5785935                         0.119781  0.002110                0.0   
6090033                         0.010407  0.001084                0.0   
6136197                         0.003456  0.001387                0.0   
6019545                         0.032782  0.000026                0.0   
5792247                         0.023951  0.000416                0.0   

                  Number of Dependents  Has First Hearing Date  \
Claim Identifier                                                 
5785935                       1.000000                       1   
6090033                       0.833333                       1   
6136197                       0.333333                       1   
6019545                       0.333333                       1   
5792247                       1.000000                       1   

                  Alternative Dispute Resolution_U  \
Claim Identifier                                     
5785935                                        0.0   
6090033                                        0.0   
6136197                                        0.0   
6019545                                        0.0   
5792247                                        0.0   

                  Alternative Dispute Resolution_Y  Attorney/Representative_Y  \
Claim Identifier                                                                
5785935                                        0.0                        1.0   
6090033                                        0.0                        1.0   
6136197                                        0.0                        0.0   
6019545                                        0.0                        0.0   
5792247                                        0.0                        1.0   

                  Carrier Type_2A. SIF  C

In [ ]:
 # Initialize RandomForest model
rf_model = RandomForestClassifier(random_state=42)

 # Set up cross-validation strategy
cv_strategy = StratifiedKFold(n_splits=5)

 # Set up RFECV with RandomForest and cross-validation
rfecv = RFECV(estimator=rf_model, step=1, cv=cv_strategy, scoring='accuracy')   #You can change scoring metric if needed

 # Fit RFECV
rfecv.fit(X_train_encoded, y_train)

 # Get the selected features
selected_features = X_train.columns[rfecv.support_].tolist()
optimal_num_features = rfecv.n_features_

print("Optimal number of features:", optimal_num_features)
print("Selected Features:", selected_features)

 # Now 'selected_features' contains the list of features selected by RFECV

## 4. Models


### 4.1 Random Forest

In [ ]:
# # 4. Build a simple model and assess the performance
# # Split data into training and validation sets

# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import classification_report, confusion_matrix
# from sklearn.model_selection import cross_val_score, train_test_split

# # Train a Random Forest model
# model = RandomForestClassifier(random_state=42)
# model.fit(X_train, y_train)

# # Cross-validation
# cv_scores = cross_val_score(model, X_train, y_train, cv=5)
# print("Cross-validation Scores:\n", cv_scores)
# print("Mean Cross-validation Score:", np.mean(cv_scores))

# # Predictions on validation set
# y_pred = model.predict(X_val)

# # Performance metrics
# print("Classification Report:\n", classification_report(y_val, y_pred))
# print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))